---
device_role: hub

interfaces:
  config:
    - name: GigabitEthernet1
      description: 'Management Interface'
      enabled: True
    - name: GigabitEthernet2
      description: 'WAN interface'
      enabled: True
    - name: GigabitEthernet3
      description: 'Core interface'
      enabled: True
  state: merged


bgp:
  config:
    bgp_as: 65000
    log_neighbor_changes: True
    neighbors:
      - neighbor: 169.254.100.1
        remote_as: 65001
      - neighbor: 169.254.100.2
        remote_as: 65001
      - neighbor: 169.254.100.3
        remote_as: 65001
      - neighbor: 169.254.100.4
        remote_as: 65001
  operation: merge

...