---

- name: DEPLOY DMVPN ON IOS XE
  hosts: all
  gather_facts: no

  vars:
    backup: false
    enable_nc: false

  tasks:

    - name: backup per platform
      include_tasks: tasks/backup_{{ ansible_network_os }}.yml
      when: backup|bool
      tags: ['backup', ]

    - name: enable NETCONF
      include_tasks: tasks/enable_nc_{{ ansible_network_os }}.yml
      when: enable_nc|bool
      tags: ['netconf', ]

    - name: configure interfaces
      include_tasks: tasks/interfaces_{{ ansible_network_os }}.yml

    - name: configure BGP
      include_tasks: tasks/bgp_{{ ansible_network_os }}.yml

    # - name: configure DMVPN
    #   include_tasks: tasks/bgp_{{ ansible_network_os }}.yml
