---

- name: set timestamp
  set_fact:
    timestamp: "{{ lookup('pipe','date +%Y-%m-%d-%H-%M-%S') }}"
  delegate_to: localhost

- name: backup IOS configs
  ios_config:
    backup: yes
    backup_options:
      filename: "{{ inventory_hostname }}_{{ timestamp }}.cfg"
      dir_path: backups