---
hub:
  R5:
    host: 10.246.48.78
    ssh_port: 2275
    netconf_port: 875
    device_params: { 'name': 'csr'}

spoke:
  R1:
    host: 10.246.48.78
    ssh_port: 2271
    netconf_port: 871
    device_params: { 'name': 'csr'}
  R2:
    host: 10.246.48.78
    ssh_port: 2272
    netconf_port: 872
    device_params: { 'name': 'csr'}
  R3:
    host: 10.246.48.78
    ssh_port: 2273
    netconf_port: 873
    device_params: { 'name': 'csr'}
  R4:
    host: 10.246.48.78
    ssh_port: 2274
    netconf_port: 874
    device_params: { 'name': 'csr'}

...