---

l3_interfaces:
  config:
    - name: loopback0
      ipv4:
        - address: 150.1.3.3/32
      ipv6:
        - address: 2001:150:3:3::3/128
    - name: GigabitEthernet1
      ipv4:
      - address: 172.16.1.173/24
    - name: GigabitEthernet2
      ipv4:
        - address: 169.254.100.3/24
      ipv6:
        - address: 2001:169:254:100::3/64


bgp_router_id: 155.1.3.3
bgp_networks:
  - prefix: 155.1.3.3
    masklen: 32